### PR TITLE
Worked from Patrick

### PR DESCRIPTION
**Pull request by ericaddison**
@psigourney 
Added some admin options, so if you log in with the Admin option checked then you get access to an additional admin menu where you can list all users and all streams.

Also did some cleanup in `Main.py`

### CODE REVIEW

**Comment by ericaddison** [comment]
Merging so we can move on!

**Comment by psigourney** [comment]
I'm thinking the data model might need to change.... I was thinking in
terms of relational databases, and ndb doesn't work that way.
Instead it allows columns with repeated values (lists).

So Streams would have a Subscribers column, which would be a list of
StreamUser keys.
Also a Tags column with a list of Tag keys.

I asked about this on StackOverflow, so I'll give it a little time to see
if there are any replies, but I think it's a better method than using the
StreamTag, and StreamSubscriber models.

Stream could even contain a list of the StreamItem keys.

https://stackoverflow.com/questions/46495723/gae-ndb-query-on-list

I think it will make things a lot easier.

**Comment by ericaddison** [comment]
hmmmmm, I might disagree...

I prefer your initial approach to the double-list approach because that would require us to maintain two lists in order to track subscriptions, which could be error prone. Also, imagine having a really popular stream that has lots of people subscribing and unsubscribing all the time. In your initial schema, this is no problem because a subscription is a separate entity, and can easily be added or deleted. In the list based approach, the same list needs to be modified all the time as users subscribe or unsubscribe... 

I can barely see the difference in how easy it would be to _retrieve_ the correct lists, something like:
```python
stream = get_a_stream_somehow()
subscribers = stream.subList
```
to get the list of subscribers if a stream actually maintains its own list, or
```python
stream = get_a_stream_somehow()
subList = StreamSubscriber.query(StreamSubscriber.stream == stream.key).fetch() 
subscribers = [ sub.user for sub in subList]
```
Not a big deal in my opinion
BUT...

**Comment by ericaddison** [comment]
I think adding subscribers gets tricky.
Here is how we could add a subscriber the current way
```python
user = get_user_somehow()
stream = get_stream_somehow()
new_sub = StreamSubscriber(user=user.key, stream=stream.key).put()
```
but with two lists...
```python
user = get_user_somehow()
stream = get_stream_somehow()
user.subscriptions.append(stream)
stream.subscribers.append(user)
```
ok, maybe the code is not that much worse... I still like the original idea better :)
I just like the idea of only having to modify one thing! And how concurrent operations are not an issue at all...

**Comment by ericaddison** [comment]
And plus, did we ever decide if you can really store a reference to an entity? Or would it just make a copy? I think a copy would not be what we want.

I remember you mentioned the `ReferenceProperty` type, but I think that is not preferred anymore since it is part of the old DB library (not NDB)...

**Comment by psigourney** [comment]
I think with the Reference type, it actually stored the object.  But the
Key type we're currently using, it's a just the key value.

I'm still just hitting a wall in terms of retrieving the values from the
data store.  I tried a couple different options:

{{ stream.user.get() }}

and

{% StreamUser.query(StreamUser.key == stream.user).get()  %}

to pull the stream owner information for the subscribed streams on the
Manage page, but both options throw errors.

**Comment by ericaddison** [comment]
hmmm, maybe try
```
{{ stream.user.key.get() }}
```

**Comment by ericaddison** [comment]
OK one sec, I'll give that a try in html...

**Comment by ericaddison** [comment]
Well, possibly that could be because I changed the name of the field in `Stream` from `user` to `owner`!
This worked for me in an HTML template (using Jinja)
```
{{ stream.owner.get().email }}
```

or it also worked without the `.email`, and just printed the whole user

**Comment by ericaddison** [comment]
I think your second example did not work because the code in a Jinja template does not have all the same imports as your py file. Try passing in `StreamUser` in the `template_values` dictionary:
```
template_values = {
  'StreamUser': StreamUser,
  ...
}
# render template as normal
```

Then I think
```
{{ StreamUser.query(StreamUser.key == stream.user).get()  }}
```
will work just fine

**Pull request merged**
