### PR TITLE
Patrick geomap

### PR DESCRIPTION
**Pull request by psigourney**
GeoMap working for all stream items on the main GeoMap page, and stream-specific GeoMaps added to the ViewStream page.

Working according to requirements, with the exception of the date slider functionality. The slider is visible, but no function is attached to it yet.

### CODE REVIEW

**Comment by ericaddison** [comment]
Cool! I will take a look at this tonight.

**Comment by ericaddison** [comment]
Cool map! I see new images that I upload with geo information show up on the map. neat!

I'll maybe work on the image thumbnail to help out :)

**Comment by ericaddison** [comment]
@psigourney 
Hey Patrick,
I added clickability to the markers that brings you directly to that picture on the viewstream page. I was working over an older commit and had to fix conflicts, so if this stomps on any of your important stuff please revert!

**Comment by psigourney** [comment]
Looks good.

**Comment by psigourney** [comment]
Date sliders appear correctly, but still don't do anything.

**Comment by psigourney** [comment]
Think this is the final version of the GeoMap

**Comment by mspagon** [comment]
When I try to create a stream on this branch I get this error:

Investigating.

**Internal Server Error**

The server has either erred or is incapable of performing the requested operation.

Traceback (most recent call last):
  File "C:\Users\mspagon\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\lib\webapp2-2.5.2\webapp2.py", line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File "C:\Users\mspagon\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\lib\webapp2-2.5.2\webapp2.py", line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File "C:\Users\mspagon\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\lib\webapp2-2.5.2\webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "C:\Users\mspagon\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\lib\webapp2-2.5.2\webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "C:\Users\mspagon\Desktop\APT_miniProject\source\Framework\BaseHandler.py", line 14, in dispatch
    webapp2.RequestHandler.dispatch(self)
  File "C:\Users\mspagon\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\lib\webapp2-2.5.2\webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "C:\Users\mspagon\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\lib\webapp2-2.5.2\webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "C:\Users\mspagon\Desktop\APT_miniProject\source\views\ViewStream.py", line 141, in get
    'item_data': item_data,
UnboundLocalError: local variable 'item_data' referenced before assignment

**Comment by mspagon** [comment]
I'm guessing the indention wrong, the code works when I remove a tab.

Wrong?
image

Right?
image

Testing and working towards a commit.

**Comment by ericaddison** [comment]
Good catch on that one. probably a merge conflict artifact

**Pull request merged**
